FROM openjdk:17-jdk-alpine

WORKDIR usr/src/app

ARG JAR_FILE=build/libs/*.jar

COPY ${JAR_FILE} app.jar

ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG MYSQL_HOST
ARG MYSQL_DATABASE
ARG MYSQL_PORT
ARG DOCKER_USERNAME

ENV MYSQL_USERNAME=${MYSQL_USERNAME}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ENV MYSQL_HOST=${MYSQL_HOST}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_PORT=${MYSQL_PORT}
ENV DOCKER_USERNAME=${DOCKER_USERNAME}

ENTRYPOINT ["java", "-jar", "app.jar"]