spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB

  sql:
    init:
      mode: always

cloud:
  aws:
    s3:
      bucket: kukerton
    credentials:
      access-key: AKIAW3MEDNH2YLXQ2JTU
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false